django/SHA1/SHA1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from calc.views import IndexView

urlpatterns = [
    url(r'^$',IndexView.as_view(), name='home'),
    url(r'^calc/',include('calc.urls', namespace='calc')),
    url(r'^admin/', admin.site.urls),
]

django/SHA1/calc/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^upload/$', views.upload_file, name='upload'),
    url(r'^success/url/$', views.upload_success, name='success'),
    ]

django/SHA1/calc/models.py
import datetime, os
from django.db import models
from django.utils import timezone, module_loading

class File(models.Model):
    settings = module_loading.import_module(os.environ['DJANGO_SETTINGS_MODULE'])
    base = settings.MEDIA_ROOT
    upl_date = models.DateTimeField('date uploaded')
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='files/%Y/%m/%d')
    sha = models.CharField('SHA1',max_length=64,default="")
    size = models.IntegerField('Size in Byte(s)',default=0)
    def abspath(self):
        return os.path.join(File.base,self.file.url)
    def __str__(self):
        return self.title
    def ctime(self):
        time = os.path.getctime(self.abspath())
        return datetime.datetime.fromtimestamp(time,timezone.get_current_timezone())
    ctime.short_description = 'Date Created'
    def mtime(self):
        time = os.path.getmtime(self.abspath())
        return datetime.datetime.fromtimestamp(time,timezone.get_current_timezone())
    mtime.short_description = 'Date Modified'
    def was_uploaded_recently(self):
        now = timezone.now()
        return now >= self.upl_date >= now - datetime.timedelta(days=1)
    was_uploaded_recently.admin_order_field = 'upl_date'
    was_uploaded_recently.boolean = True
    was_uploaded_recently.short_description = 'Uploaded recently?'
    def show(self):
        return zip(('title', 'file', 'size', 'upload date',
                    'create time', 'modify time'),
                   (self.title, self.file, self.size, self.upl_date,
                    self.ctime(), self.mtime()))

django/SHA1/calc/forms.py
from django.forms import ModelForm
from .models import File

class ModelFormWithFileField(ModelForm):
    class Meta:
        model = File
        fields = ['upl_date', 'title', 'file']

django/SHA1/calc/views.py
import os

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from hashlib import sha1

from .models import File
from .forms import ModelFormWithFileField

class IndexView(generic.ListView):
    template_name = 'calc/index.html'
    context_object_name = 'latest_file_list'

    def get_queryset(self):
        """
        Return the last five uploaded files (not including those set to be
        published in the future).
        """
        return File.objects.filter(upl_date__lte=timezone.now()).order_by('-upl_date')[:5]

class DetailView(generic.DetailView):
    model = File
    template_name = 'calc/detail.html'
    def get_queryset(self):
        """
        Excludes any files that aren't published yet.
        """
        return File.objects.filter(upl_date__lte=timezone.now())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not context['file'].sha:
            path = context['file'].abspath()
            s = sha1()
            with open(path,'rb')as f:
                while 1:
                    chunk = f.read(4096)
                    s.update(chunk)
                    if not chunk:break
            context['file'].size = os.path.getsize(path)
            context['file'].sha = s.hexdigest()
            context['file'].save()
        return context

def upload_file(request):
    if request.method == 'POST':
        form = ModelFormWithFileField(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('calc:success'))
    else:
        form = ModelFormWithFileField(initial={'upl_date': timezone.now()})
    return render(request, 'calc/upload.html', {'form':form})

def upload_success(request):
    return render(request, 'calc/success.html')

django/SHA1/calc/templates/calc/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href={% static 'calc/style.css' %} />
    <title>{% block title %}Ceilopty's site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href={% url 'calc:upload'%}>Upload</a></li>
			<li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

django/SHA1/calc/templates/calc/detail.html
{% extends "calc/base.html" %}

{% block content %}
<h1>{{ file.title }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table>
	{% if file.show %}
	{% for name, value in file.show %}
	<tr>
		<td>{{ name|title }}</td>
		<td>{{ value }}</td>
	</tr>
	{% endfor %}
	{% endif %}

	<tr>
		<td>SHA1</td>
		<td>{{ file.sha }}</td>
	</tr>
	
	
</table>
{% endblock %}



django/SHA1/calc/templates/calc/index.html
{% extends "calc/base.html" %}

{% block content %}
{% if latest_file_list %}
    <ul>
    {% for file in latest_file_list %}
        <li><a href="{% url 'calc:detail' file.id %}">{{ file.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No files are available.</p>
{% endif %}
{% endblock %}

django/SHA1/calc/templates/calc/success.html
{% extends "calc/base.html" %}
{% block content %}
<h1>UPLOAD SUCCESS</h1>
{% endblock %}


django/SHA1/calc/templates/calc/upload.html
{% extends "calc/base.html" %}
{% block content %}
<h1>UPLOAD Test</h1>
<form enctype="multipart/form-data" method="post" action="./">
{% csrf_token %}
{# {{ form }} #}
{% block field_sets %}
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}
<input type="submit" value="Upload" />
</form>
{% endblock %}
